job('Fist_Maven_Project_Via_DSL'){
    description("first maven job generated by DSL")
	scm{
	    git("https://github.com/barochiyavikas/Jenkins_Upgradev3.git", master)
	}
	triggers{
	    scm('* * * * *')    
	}
	steps{
	    maven('clean package', 'maven-samples/single-module/pom.xml')
	}
	publishers{
	    archiveArtifacts '**/*.jar'
	}
}
